services:
  - type: web
    name: chatbot-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python backend/app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: your-api-key-here
